### ISSUE TITLE
Create zip file

### ISSUE THREAD

**Issue by sadending-ios** [DevelopCubeLab/ExtractApp#1]
If package an encrypted app, I think need to add iTunesMetadata.plist file (Peer to .app folder), this seems to avoid some errors when pay or restore receipt.

**Comment by DevelopCubeLab** [comment]
However, iTunesMetadata.plist is included, and the system will automatically delete it during installation, so it is not very useful. I can consider adding this file.

**Comment by sadending-ios** [comment]
After the app is installed, iTunesMetadata.plist file will be located next to the .app folder, if repackaging the app to an ipa, place the iTunesMetadata.plist file outside the Payload folder then create a zip containing the Payload folder and the iTunesMetadata.plist file.
That's all I know.

**Comment by DevelopCubeLab** [comment]
There is no problem with this. I have tried including this file. When you install this ipa to other devices, this file will be automatically deleted by the system. You can use Filza to get the answers you need, so there is actually no big problem. Function, I will add this file in the next version, but don't hold out hope, if you want to install to other devices you need to use Filza to copy this file

**Comment by sadending-ios** [comment]
Do you have Telegram?
